//! Emit layer: walks a `ResolvedScl` once and produces the `TokenStream` that
//! builds an `IedModel`.
//!
//! Structure:
//!
//! - [`emit_file`] - top level; one `pub fn build_<X>_model() -> IedModel` per IED
//! - `emit_ied_fn` - a single IED into a function body
//! - `emit_ld_expr` - a logical device into a `LogicalDeviceBuilder` chain
//! - `emit_ln_expr` - a logical node into a `LogicalNodeBuilder` chain, with its
//!   data sets, four control block kinds, SGCB and DOI overrides
//! - `emit_do_type_expansion` - recursive DO and SDO expansion
//! - `emit_da_expr` / `emit_bda_expr` - DA and BDA, including the recursion into
//!   a constructed bType
//! - `emit_dataset_expr` / `emit_fcda_expr` - data sets and their members
//! - `emit_rcb_expr` / `emit_gocb_expr` / `emit_svcb_expr` / `emit_lcb_expr` /
//!   `emit_sgcb_expr`
//! - `emit_doi_overrides` - the post-build walk that applies DOI, SDI and DAI
//!   default-value overrides
//!
//! Each emit function follows its counterpart in `iec61850_scl::build_model`
//! almost line for line; `let x = build_xxx(arg)?` there becomes
//! `let x_tokens = emit_xxx_expr(arg)?` here. Every conversion from a string to
//! an enum, and from a bType to a data attribute type, calls the same
//! `__build_internals` helper the runtime path uses, so generated and runtime
//! models cannot diverge.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use iec61850_scl::__build_internals::{
    parse_fc, parse_val_for_b_type, pick_val_for_no_sgroup, MmsValue,
};
use iec61850_scl::raw::{
    DataTypeTemplates, RawBda, RawDaDef, RawDaType, RawDai, RawDataInstance, RawDataSet, RawDoDef,
    RawDoType, RawFcda, RawGseControl, RawIed, RawLogControl, RawLogicalDevice, RawLogicalNode,
    RawReportControlBlock, RawSampledValueControl, RawScl, RawSdi, RawSdoDef, RawSettingControl,
};
use iec61850_scl::ResolvedScl;

use crate::tokens::{
    emit_dat_value, emit_default_mms_value, emit_fc_value, emit_mms_value, emit_opt_flds,
    emit_report_trg_ops, emit_trg_ops,
};
use crate::{CompileBuilder, CompileError};

// -----------------------------------------------------------------------------
// 0. Top level
// -----------------------------------------------------------------------------

/// Emits the entire contents of `model.rs`.
///
/// Produces one `pub fn build_<ied_name>_model() -> IedModel` per IED in the
/// `ResolvedScl`. When the file holds several IEDs and
/// `cfg.requested_ied_name()` names one, only that IED is emitted.
///
/// # Errors
///
/// [`CompileError::Emit`] when the requested IED is absent, and whatever a
/// nested emit step reports.
pub fn emit_file(
    resolved: &ResolvedScl,
    cfg: &CompileBuilder,
) -> Result<TokenStream, CompileError> {
    let raw = resolved.raw();

    // `raw.ieds` keeps the order of the SCL document; deterministic mode sorts by name.
    let mut target_ieds: Vec<&RawIed> = match cfg.requested_ied_name() {
        Some(name) => raw.ieds.iter().filter(|i| i.name == name).collect(),
        None => raw.ieds.iter().collect(),
    };
    if cfg.is_deterministic() {
        target_ieds.sort_by(|a, b| a.name.cmp(&b.name));
    }

    if target_ieds.is_empty() {
        return Err(CompileError::Emit(format!(
            "target IED not found: requested={:?}, available={:?}",
            cfg.requested_ied_name(),
            raw.ieds.iter().map(|i| &i.name).collect::<Vec<_>>(),
        )));
    }

    let fns = target_ieds
        .iter()
        .map(|ied| emit_ied_fn(ied, raw, cfg))
        .collect::<Result<Vec<_>, _>>()?;

    let header = quote! {
        // --- auto-generated by iec61850-scl-build --- DO NOT EDIT ---
        // The generated code reaches the model types through a codegen-private
        // re-export, so a user crate need not depend on `iec61850-model`.
        //
        // The file is pulled in with `include!()`, which rejects inner
        // attributes, so every lint attribute is an outer `#[...]` on the
        // emitted item. The `use` block carries its own
        // `#[allow(unused_imports)]`, because not every SCL file uses every
        // control block type.
        #[allow(unused_imports)]
        use ::iec61850_scl::__rt::{
            IedModelBuilder, LogicalDeviceBuilder, LogicalNodeBuilder, DataObjectBuilder,
            ReportControlBlock, GooseControlBlock, SvControlBlock, LogControlBlock,
            SettingGroupControlBlock,
            FC, DataAttribute, DataObject, DataSet, DataSetEntry, IedModel,
            DataAttributeType, TrgOps, MmsValue,
        };
    };

    Ok(quote! {
        #header
        #(#fns)*
    })
}

/// Emits one IED as `pub fn build_<X>_model() -> IedModel`.
///
/// Walks the IED, its access points, its server and its logical devices. The
/// generated code uses `expect("codegen: ...")` where the runtime path uses
/// `?`, because the build script has already checked every invariant: a builder
/// failure is a defect, and is reported while the build script runs.
fn emit_ied_fn(
    ied: &RawIed,
    raw: &RawScl,
    cfg: &CompileBuilder,
) -> Result<TokenStream, CompileError> {
    let fn_name = format_ident!("build_{}_model", sanitize_ident(&ied.name));
    let ied_name_lit = ied.name.as_str();
    let dtt = &raw.data_type_templates;

    // Collect every logical device, across all access points and servers.
    let mut lds: Vec<&RawLogicalDevice> = Vec::new();
    for ap in &ied.access_points {
        if let Some(server) = &ap.server {
            for ld in &server.logical_devices {
                lds.push(ld);
            }
        }
    }
    if cfg.is_deterministic() {
        lds.sort_by(|a, b| a.inst.cmp(&b.inst));
    }
    if lds.is_empty() {
        return Err(CompileError::Emit(format!(
            "IED `{}` has no LDevice; the runtime path reports MissingRequiredElement",
            ied.name
        )));
    }

    let ld_exprs = lds
        .iter()
        .map(|ld| emit_ld_expr(ld, dtt, cfg))
        .collect::<Result<Vec<_>, _>>()?;

    Ok(quote! {
        /// Generated IED model.
        // Outer `#[allow]`: the function reaches the user crate through
        // `include!()`, which rejects inner attributes.
        #[allow(non_snake_case, clippy::all, dead_code)]
        pub fn #fn_name() -> IedModel {
            let mut __m = IedModelBuilder::new(#ied_name_lit);
            #(
                __m = __m
                    .add_ld(#ld_exprs)
                    .expect("codegen: IedModelBuilder::add_ld failed");
            )*
            __m.build().expect("codegen: IedModelBuilder::build failed")
        }
    })
}

// -----------------------------------------------------------------------------
// 1. LogicalDevice
// -----------------------------------------------------------------------------

/// Emits a logical device as a
/// `LogicalDeviceBuilder::new(...).add_ln(...).build()` expression.
fn emit_ld_expr(
    ld: &RawLogicalDevice,
    dtt: &DataTypeTemplates,
    cfg: &CompileBuilder,
) -> Result<TokenStream, CompileError> {
    let inst_lit = ld.inst.as_str();
    let with_ld_name = ld.ld_name.as_deref().map(|n| {
        quote! { __ld = __ld.with_ld_name(#n); }
    });

    // Deterministic mode sorts the logical nodes by (prefix, class, inst), but
    // LLN0 has to stay first: the model builder rejects any other order with
    // InvalidParent.
    let mut lns: Vec<&RawLogicalNode> = ld.logical_nodes.iter().collect();
    if cfg.is_deterministic() {
        lns.sort_by(|a, b| {
            // LLN0 always sorts first; otherwise compare (prefix, class, inst).
            let a_is_lln0 = a.ln_class == "LLN0";
            let b_is_lln0 = b.ln_class == "LLN0";
            match (a_is_lln0, b_is_lln0) {
                (true, false) => std::cmp::Ordering::Less,
                (false, true) => std::cmp::Ordering::Greater,
                _ => (
                    a.prefix.as_deref().unwrap_or(""),
                    a.ln_class.as_str(),
                    a.inst.as_str(),
                )
                    .cmp(&(
                        b.prefix.as_deref().unwrap_or(""),
                        b.ln_class.as_str(),
                        b.inst.as_str(),
                    )),
            }
        });
    }

    let ln_exprs = lns
        .iter()
        .map(|ln| emit_ln_expr(ln, dtt, &ld.inst, cfg))
        .collect::<Result<Vec<_>, _>>()?;

    Ok(quote! {
        {
            let mut __ld = LogicalDeviceBuilder::new(#inst_lit);
            #with_ld_name
            #(
                __ld = __ld.add_ln(#ln_exprs);
            )*
            __ld.build().expect("codegen: LogicalDeviceBuilder::build failed")
        }
    })
}

// -----------------------------------------------------------------------------
// 2. LogicalNode
// -----------------------------------------------------------------------------

/// Emits a logical node as `{ let mut __ln = ...; __ln.add_do(...); ...;
/// let __ln = __ln.build()...; <DOI overrides>; __ln }`.
fn emit_ln_expr(
    ln: &RawLogicalNode,
    dtt: &DataTypeTemplates,
    ld_inst: &str,
    cfg: &CompileBuilder,
) -> Result<TokenStream, CompileError> {
    let prefix_lit = ln.prefix.as_deref().unwrap_or("");
    let ln_class_lit = ln.ln_class.as_str();
    let inst_lit = ln.inst.as_str();

    // The resolve stage has already checked that ln_type_ref exists.
    let lnt = dtt.ln_node_types.get(&ln.ln_type_ref).ok_or_else(|| {
        CompileError::Emit(format!(
            "LN ln_type_ref `{}` is absent from ln_node_types; the resolve stage should have rejected it",
            ln.ln_type_ref
        ))
    })?;

    // The DO order inside an LNodeType comes from the SCL and is preserved;
    // determinism is handled at logical device and logical node level.
    let do_exprs = lnt
        .dos
        .iter()
        .map(|do_def| emit_do_expr(do_def, dtt))
        .collect::<Result<Vec<_>, _>>()?;

    // Data sets, sorted for determinism.
    let mut datasets: Vec<&RawDataSet> = ln.data_sets.iter().collect();
    if cfg.is_deterministic() {
        datasets.sort_by(|a, b| a.name.cmp(&b.name));
    }
    let dataset_exprs = datasets
        .iter()
        .map(|ds| emit_dataset_expr(ds, ld_inst, ln))
        .collect::<Result<Vec<_>, _>>()?;

    // The four control block kinds, sorted for determinism.
    let rcb_exprs = sorted_by_name(ln.report_controls.iter(), cfg, |r| r.name.as_str())
        .into_iter()
        .map(emit_rcb_expr)
        .collect::<Vec<_>>();
    let gocb_exprs = sorted_by_name(ln.gse_controls.iter(), cfg, |g| g.name.as_str())
        .into_iter()
        .map(emit_gocb_expr)
        .collect::<Vec<_>>();
    let svcb_exprs = sorted_by_name(ln.smv_controls.iter(), cfg, |s| s.name.as_str())
        .into_iter()
        .map(emit_svcb_expr)
        .collect::<Vec<_>>();
    let lcb_exprs = sorted_by_name(ln.log_controls.iter(), cfg, |l| l.name.as_str())
        .into_iter()
        .map(emit_lcb_expr)
        .collect::<Vec<_>>();

    let sgcb_apply = match ln.setting_control.as_ref() {
        Some(sgcb) => {
            let expr = emit_sgcb_expr(sgcb, ln, ld_inst)?;
            Some(quote! { __ln = __ln.set_sgcb(#expr); })
        }
        None => None,
    };

    // DOI overrides mutate the `Arc<RwLock<MmsValue>>` after `ln.build()`.
    let override_stmts = emit_doi_overrides(ln, dtt, ld_inst)?;

    Ok(quote! {
        {
            let mut __ln = LogicalNodeBuilder::new(#prefix_lit, #ln_class_lit, #inst_lit);
            #( __ln = __ln.add_do(#do_exprs); )*
            #( __ln = __ln.add_dataset(#dataset_exprs); )*
            #( __ln = __ln.add_rcb(#rcb_exprs); )*
            #( __ln = __ln.add_gocb(#gocb_exprs); )*
            #( __ln = __ln.add_svcb(#svcb_exprs); )*
            #( __ln = __ln.add_lcb(#lcb_exprs); )*
            #sgcb_apply
            let __ln = __ln.build().expect("codegen: LogicalNodeBuilder::build failed");
            #( #override_stmts )*
            __ln
        }
    })
}

// -----------------------------------------------------------------------------
// 3. DataObject / SDO
// -----------------------------------------------------------------------------

/// Emits a data object as
/// `DataObjectBuilder::scalar(...).add_da_node(...).add_sub_do(...).build()`.
fn emit_do_expr(do_def: &RawDoDef, dtt: &DataTypeTemplates) -> Result<TokenStream, CompileError> {
    let dot = dtt.do_types.get(&do_def.do_type_ref).ok_or_else(|| {
        CompileError::Emit(format!(
            "DO type_ref `{}` is absent from do_types; the resolve stage should have rejected it",
            do_def.do_type_ref
        ))
    })?;
    emit_do_type_expansion(&do_def.name, dot, dtt)
}

fn emit_do_type_expansion(
    name: &str,
    dot: &RawDoType,
    dtt: &DataTypeTemplates,
) -> Result<TokenStream, CompileError> {
    let name_lit = name;

    let da_exprs = dot
        .das
        .iter()
        .map(|da| emit_da_expr(da, dtt))
        .collect::<Result<Vec<_>, _>>()?;

    let sdo_exprs = dot
        .sdos
        .iter()
        .map(|sdo| emit_sdo_expr(sdo, dtt))
        .collect::<Result<Vec<_>, _>>()?;

    Ok(quote! {
        {
            let mut __do = DataObjectBuilder::scalar(#name_lit);
            #( __do = __do.add_da_node(#da_exprs); )*
            #( __do = __do.add_sub_do(#sdo_exprs); )*
            __do.build().expect("codegen: DataObjectBuilder::build failed")
        }
    })
}

fn emit_sdo_expr(sdo: &RawSdoDef, dtt: &DataTypeTemplates) -> Result<TokenStream, CompileError> {
    let dot = dtt.do_types.get(&sdo.do_type_ref).ok_or_else(|| {
        CompileError::Emit(format!(
            "SDO type_ref `{}` is absent from do_types; the resolve stage should have rejected it",
            sdo.do_type_ref
        ))
    })?;
    emit_do_type_expansion(&sdo.name, dot, dtt)
}

// -----------------------------------------------------------------------------
// 4. DataAttribute / BDA
// -----------------------------------------------------------------------------

/// Emits a data attribute as `DataAttribute::new(...)`, or as
/// `DataAttribute::constructed(...)` when its bType is a structure.
///
/// Every bType-to-type, fc-to-FC and trigger-option conversion calls the
/// runtime helper.
fn emit_da_expr(da: &RawDaDef, dtt: &DataTypeTemplates) -> Result<TokenStream, CompileError> {
    // The functional constraint goes through the runtime helper; an unknown
    // token becomes an SclParseError.
    let fc = parse_fc(
        &da.fc, da.span,
        // The path only decorates the error message, and the build script has
        // already validated the input, so a placeholder is enough.
        "DA",
    )
    .map_err(CompileError::ResolveScl)?;
    let fc_tok = emit_fc_value(fc);
    let trg_tok = emit_trg_ops(da.trg_ops);
    let name_lit = da.name.as_str();

    if da.b_type == "Struct" {
        let type_id = da.type_ref.as_deref().ok_or_else(|| {
            CompileError::Emit(format!("DA `{}` has bType=Struct but no type_ref", da.name))
        })?;
        let dat = dtt.da_types.get(type_id).ok_or_else(|| {
            CompileError::Emit(format!(
                "DA `{}` type_ref `{}` is absent from da_types; the resolve stage should have rejected it",
                da.name, type_id
            ))
        })?;
        let child_exprs = dat
            .bdas
            .iter()
            .map(|bda| emit_bda_expr(bda, &fc_tok, dtt))
            .collect::<Result<Vec<_>, _>>()?;
        // Matches the runtime path: a constructed DA, then its trigger options.
        return Ok(quote! {
            {
                let mut __da = DataAttribute::constructed(
                    ::std::string::String::from(#name_lit),
                    #fc_tok,
                    ::std::vec![ #( #child_exprs ),* ],
                );
                __da.trg_ops = #trg_tok;
                __da
            }
        });
    }

    // Leaf DA: the type comes from `b_type_to_dat` and the initial value from
    // `emit_default_mms_value`.
    let dat = iec61850_scl::__build_internals::b_type_to_dat(&da.b_type, da.span, "DA")
        .map_err(CompileError::ResolveScl)?;
    let dat_tok = emit_dat_value(dat);
    let initial_tok = emit_default_mms_value(dat);

    Ok(quote! {
        DataAttribute::new(
            ::std::string::String::from(#name_lit),
            #fc_tok,
            #dat_tok,
            #trg_tok,
            #initial_tok,
        )
    })
}

/// Emits a BDA as a `DataAttribute`.
///
/// A BDA has no functional constraint of its own and inherits the one of its
/// parent DA or BDA.
fn emit_bda_expr(
    bda: &RawBda,
    parent_fc: &TokenStream,
    dtt: &DataTypeTemplates,
) -> Result<TokenStream, CompileError> {
    let name_lit = bda.name.as_str();

    if bda.b_type == "Struct" {
        let type_id = bda.type_ref.as_deref().ok_or_else(|| {
            CompileError::Emit(format!(
                "BDA `{}` has bType=Struct but no type_ref",
                bda.name
            ))
        })?;
        let dat = dtt.da_types.get(type_id).ok_or_else(|| {
            CompileError::Emit(format!(
                "BDA `{}` type_ref `{}` is absent from da_types; the resolve stage should have rejected it",
                bda.name, type_id
            ))
        })?;
        let child_exprs = dat
            .bdas
            .iter()
            .map(|child| emit_bda_expr(child, parent_fc, dtt))
            .collect::<Result<Vec<_>, _>>()?;
        return Ok(quote! {
            DataAttribute::constructed(
                ::std::string::String::from(#name_lit),
                #parent_fc,
                ::std::vec![ #( #child_exprs ),* ],
            )
        });
    }

    let dat = iec61850_scl::__build_internals::b_type_to_dat(&bda.b_type, bda.span, "BDA")
        .map_err(CompileError::ResolveScl)?;
    let dat_tok = emit_dat_value(dat);
    let initial_tok = emit_default_mms_value(dat);

    Ok(quote! {
        DataAttribute::new(
            ::std::string::String::from(#name_lit),
            #parent_fc,
            #dat_tok,
            TrgOps::NONE,
            #initial_tok,
        )
    })
}

// -----------------------------------------------------------------------------
// 5. DataSet / FCDA
// -----------------------------------------------------------------------------

fn emit_dataset_expr(
    ds: &RawDataSet,
    ld_inst: &str,
    ln: &RawLogicalNode,
) -> Result<TokenStream, CompileError> {
    let name_lit = ds.name.as_str();
    let entries = ds
        .fcdas
        .iter()
        .map(|f| emit_fcda_expr(f, ld_inst, ln))
        .collect::<Result<Vec<_>, _>>()?;
    Ok(quote! {
        DataSet {
            name: ::std::string::String::from(#name_lit),
            entries: ::std::vec![ #( #entries ),* ],
        }
    })
}

fn emit_fcda_expr(
    f: &RawFcda,
    _ld_inst: &str,
    _ln: &RawLogicalNode,
) -> Result<TokenStream, CompileError> {
    let ld_inst_lit = f.ld_inst.as_str();

    // ln_name is prefix + ln_class + ln_inst, with an empty instance treated as "".
    let mut ln_name = String::new();
    if let Some(p) = &f.prefix {
        ln_name.push_str(p);
    }
    ln_name.push_str(&f.ln_class);
    if let Some(i) = &f.ln_inst {
        ln_name.push_str(i);
    }

    let fc = parse_fc(&f.fc, f.span, "FCDA").map_err(CompileError::ResolveScl)?;
    let fc_tok = emit_fc_value(fc);

    // do_path splits doName on `.`; daName becomes the final segment.
    let mut do_path: Vec<String> = Vec::new();
    if let Some(do_name) = &f.do_name {
        for seg in do_name.split('.') {
            if !seg.is_empty() {
                do_path.push(seg.to_string());
            }
        }
    }
    if let Some(da_name) = &f.da_name {
        do_path.push(da_name.clone());
    }
    let do_path_lits: Vec<&str> = do_path.iter().map(|s| s.as_str()).collect();

    let array_index_tok = match f.ix {
        Some(i) => quote! { ::std::option::Option::Some(#i) },
        None => quote! { ::std::option::Option::None },
    };

    Ok(quote! {
        DataSetEntry {
            ld_inst: ::std::string::String::from(#ld_inst_lit),
            ln_name: ::std::string::String::from(#ln_name),
            fc: #fc_tok,
            do_path: ::std::vec![ #( ::std::string::String::from(#do_path_lits) ),* ],
            array_index: #array_index_tok,
            component: ::std::option::Option::None,
        }
    })
}

// -----------------------------------------------------------------------------
// 6. Control blocks
// -----------------------------------------------------------------------------

fn emit_rcb_expr(r: &RawReportControlBlock) -> TokenStream {
    let name = r.name.as_str();
    let is_buffered = r.buffered;
    let dataset_ref = r.dat_set.clone().unwrap_or_default();
    let conf_rev = r.conf_rev;
    let rpt_id = r.rpt_id.clone().unwrap_or_default();
    let trg_ops_tok = emit_report_trg_ops(r.trg_ops);
    let opt_flds_tok = emit_opt_flds(r.opt_fields);
    let buf_tm_ms = r.buf_time;
    let intg_pd_ms = r.intg_pd;
    quote! {
        ReportControlBlock {
            name: ::std::string::String::from(#name),
            is_buffered: #is_buffered,
            dataset_ref: ::std::string::String::from(#dataset_ref),
            conf_rev: #conf_rev,
            rpt_id: ::std::string::String::from(#rpt_id),
            trg_ops: #trg_ops_tok,
            opt_flds: #opt_flds_tok,
            buf_tm_ms: #buf_tm_ms,
            intg_pd_ms: #intg_pd_ms,
        }
    }
}

fn emit_gocb_expr(g: &RawGseControl) -> TokenStream {
    let name = g.name.as_str();
    let dataset_ref = g.data_set.as_str();
    let conf_rev = g.conf_rev;
    // The SCL carries no goID, so the control block name is used instead.
    let go_id = g.name.as_str();
    quote! {
        GooseControlBlock {
            name: ::std::string::String::from(#name),
            dataset_ref: ::std::string::String::from(#dataset_ref),
            conf_rev: #conf_rev,
            go_id: ::std::string::String::from(#go_id),
        }
    }
}

fn emit_svcb_expr(s: &RawSampledValueControl) -> TokenStream {
    let name = s.name.as_str();
    let dataset_ref = s.data_set.as_str();
    let conf_rev = s.conf_rev;
    let sv_id = s.smv_id.as_str();
    let is_multicast = s.multicast;
    quote! {
        SvControlBlock {
            name: ::std::string::String::from(#name),
            dataset_ref: ::std::string::String::from(#dataset_ref),
            conf_rev: #conf_rev,
            sv_id: ::std::string::String::from(#sv_id),
            is_multicast: #is_multicast,
        }
    }
}

fn emit_lcb_expr(l: &RawLogControl) -> TokenStream {
    let name = l.name.as_str();
    let dataset_ref = l.data_set.clone().unwrap_or_default();
    let log_ref = l.log_name.clone().unwrap_or_default();
    quote! {
        LogControlBlock {
            name: ::std::string::String::from(#name),
            dataset_ref: ::std::string::String::from(#dataset_ref),
            log_ref: ::std::string::String::from(#log_ref),
        }
    }
}

/// Emits an SGCB, applying the same u8 and u16 range checks as the runtime
/// path.
///
/// A violation panics while the build script runs, so it never reaches the
/// user's binary.
fn emit_sgcb_expr(
    sgcb: &RawSettingControl,
    _ln: &RawLogicalNode,
    _ld_inst: &str,
) -> Result<TokenStream, CompileError> {
    let num_of_sg = u8::try_from(sgcb.num_of_sgs).map_err(|_| {
        CompileError::Emit(format!(
            "SGCB numOfSGs={} is out of range for u8; the standard allows 1 to 255",
            sgcb.num_of_sgs
        ))
    })?;
    let act_sg = u8::try_from(sgcb.act_sg).map_err(|_| {
        CompileError::Emit(format!(
            "SGCB actSG={} is out of range for u8; the standard allows 1 to 255",
            sgcb.act_sg
        ))
    })?;
    let has_resv_tms = sgcb.resv_tms.is_some();
    // Matching the runtime path: a value above u16::MAX is clamped, and a
    // missing value defaults to 60 s.
    let default_resv_tms_s: u16 = sgcb
        .resv_tms
        .map(|v| {
            if v > u16::MAX as u32 {
                u16::MAX
            } else {
                v as u16
            }
        })
        .unwrap_or(60);

    Ok(quote! {
        SettingGroupControlBlock {
            num_of_sg: #num_of_sg,
            act_sg: #act_sg,
            has_resv_tms: #has_resv_tms,
            default_resv_tms_s: #default_resv_tms_s,
        }
    })
}

// -----------------------------------------------------------------------------
// 7. DOI / SDI / DAI overrides
// -----------------------------------------------------------------------------

/// Flattens every DAI under `RawLogicalNode.doi` into a `(do_path, MmsValue)`
/// pair and emits the lookup and the write that applies it.
///
/// DAI strings are parsed while the build script runs, through the runtime
/// `parse_val_for_b_type` helper, and the result is emitted as a literal by
/// `emit_mms_value`, so the user's run time performs no string parsing.
///
/// Path lookup uses the model crate's existing public API
/// (`LogicalNode::do_by_name`, `DataObject::child_by_name`,
/// `DataAttribute::child_by_name`), and adds nothing to that crate.
///
/// A failing override, such as a path that does not resolve or a DAI landing on
/// a constructed DA, is warned about and skipped at run time. Here it is caught
/// while the build script runs and reported there, instead of being carried
/// into the user's binary.
fn emit_doi_overrides(
    ln: &RawLogicalNode,
    dtt: &DataTypeTemplates,
    ld_inst: &str,
) -> Result<Vec<TokenStream>, CompileError> {
    let lnt = dtt.ln_node_types.get(&ln.ln_type_ref).ok_or_else(|| {
        CompileError::Emit(format!(
            "LN ln_type_ref `{}` is absent from ln_node_types; the resolve stage should have rejected it",
            ln.ln_type_ref
        ))
    })?;

    let mut out: Vec<TokenStream> = Vec::new();
    for raw_doi in &ln.doi {
        let raw_do_def = match lnt.dos.iter().find(|d| d.name == raw_doi.name) {
            Some(d) => d,
            None => {
                tracing::warn!(
                    target: "iec61850-scl-build",
                    "DOI name=\"{}\" has no matching DO in LNodeType id=\"{}\", skipping",
                    raw_doi.name,
                    lnt.id
                );
                continue;
            }
        };
        let dot = dtt.do_types.get(&raw_do_def.do_type_ref).ok_or_else(|| {
            CompileError::Emit(format!(
                "DO type_ref `{}` is absent from do_types; the resolve stage should have rejected it",
                raw_do_def.do_type_ref
            ))
        })?;
        let path_prefix = format!(
            "SCL/.../LDevice[inst=\"{}\"]/LN[lnClass=\"{}\",inst=\"{}\"]/DOI[name=\"{}\"]",
            ld_inst, ln.ln_class, ln.inst, raw_doi.name
        );
        // path_segments is the path from the logical node down to the data
        // attribute: the DO name first, then the SDI and DAI names.
        let mut base_path: Vec<String> = vec![raw_doi.name.clone()];
        emit_instances_at_do(
            &raw_doi.children,
            dot,
            dtt,
            &path_prefix,
            &mut base_path,
            &mut out,
        )?;
    }

    Ok(out)
}

/// Flattens the SDI and DAI children of a DOType or DAType container into emit
/// statements.
///
/// `base_path` is the path from the logical node to the current position:
/// segment 0 is the DO name, followed by the SDO and SDA names. Each DAI becomes
/// one statement that walks the tree and writes the value.
fn emit_instances_at_do(
    children: &[RawDataInstance],
    dot: &RawDoType,
    dtt: &DataTypeTemplates,
    parent_path: &str,
    base_path: &mut Vec<String>,
    out: &mut Vec<TokenStream>,
) -> Result<(), CompileError> {
    for inst in children {
        match inst {
            RawDataInstance::Sdi(sdi) => {
                handle_sdi_at_do(sdi, dot, dtt, parent_path, base_path, out)?;
            }
            RawDataInstance::Dai(dai) => {
                let da_def = match dot.das.iter().find(|d| d.name == dai.name) {
                    Some(d) => d,
                    None => {
                        tracing::warn!(
                            target: "iec61850-scl-build",
                            "DAI name=\"{}\" has no matching DA in DOType id=\"{}\", skipping",
                            dai.name,
                            dot.id
                        );
                        continue;
                    }
                };
                let path = format!("{}/DAI[name=\"{}\"]", parent_path, dai.name);
                base_path.push(dai.name.clone());
                emit_dai_assignment(
                    dai,
                    da_def.b_type.as_str(),
                    da_def.type_ref.as_deref(),
                    dtt,
                    &path,
                    base_path,
                    out,
                )?;
                base_path.pop();
            }
        }
    }
    Ok(())
}

fn handle_sdi_at_do(
    sdi: &RawSdi,
    dot: &RawDoType,
    dtt: &DataTypeTemplates,
    parent_path: &str,
    base_path: &mut Vec<String>,
    out: &mut Vec<TokenStream>,
) -> Result<(), CompileError> {
    // Two possibilities: a sub-DO, or a constructed DA with bType=Struct.
    if let Some(sdo) = dot.sdos.iter().find(|s| s.name == sdi.name) {
        let sub_dot = dtt.do_types.get(&sdo.do_type_ref).ok_or_else(|| {
            CompileError::Emit(format!(
                "SDO type_ref `{}` is absent from do_types; the resolve stage should have rejected it",
                sdo.do_type_ref
            ))
        })?;
        let path = format!("{}/SDI[name=\"{}\"]", parent_path, sdi.name);
        base_path.push(sdi.name.clone());
        emit_instances_at_do(&sdi.children, sub_dot, dtt, &path, base_path, out)?;
        base_path.pop();
    } else if let Some(da_def) = dot.das.iter().find(|d| d.name == sdi.name) {
        if da_def.b_type != "Struct" {
            tracing::warn!(
                target: "iec61850-scl-build",
                "SDI name=\"{}\" resolves to a DA that is not a Struct (bType=\"{}\"), skipping",
                sdi.name,
                da_def.b_type
            );
            return Ok(());
        }
        let type_id = da_def.type_ref.as_deref().ok_or_else(|| {
            CompileError::Emit(format!(
                "DA `{}` has bType=Struct but no type_ref; the resolve stage should have rejected it",
                da_def.name
            ))
        })?;
        let dat = dtt.da_types.get(type_id).ok_or_else(|| {
            CompileError::Emit(format!(
                "DA type_ref `{}` is absent from da_types; the resolve stage should have rejected it",
                type_id
            ))
        })?;
        let path = format!("{}/SDI[name=\"{}\"]", parent_path, sdi.name);
        base_path.push(sdi.name.clone());
        emit_instances_at_da(&sdi.children, dat, dtt, &path, base_path, out)?;
        base_path.pop();
    } else {
        tracing::warn!(
            target: "iec61850-scl-build",
            "SDI name=\"{}\" has no matching SDO or DA in DOType id=\"{}\", skipping",
            sdi.name,
            dot.id
        );
    }
    Ok(())
}

fn emit_instances_at_da(
    children: &[RawDataInstance],
    dat: &RawDaType,
    dtt: &DataTypeTemplates,
    parent_path: &str,
    base_path: &mut Vec<String>,
    out: &mut Vec<TokenStream>,
) -> Result<(), CompileError> {
    for inst in children {
        match inst {
            RawDataInstance::Sdi(sdi) => {
                let bda_def = match dat.bdas.iter().find(|b| b.name == sdi.name) {
                    Some(b) => b,
                    None => {
                        tracing::warn!(
                            target: "iec61850-scl-build",
                            "SDI name=\"{}\" has no matching BDA in DAType id=\"{}\", skipping",
                            sdi.name,
                            dat.id
                        );
                        continue;
                    }
                };
                if bda_def.b_type != "Struct" {
                    tracing::warn!(
                        target: "iec61850-scl-build",
                        "SDI name=\"{}\" resolves to a BDA that is not a Struct (bType=\"{}\"), skipping",
                        sdi.name,
                        bda_def.b_type
                    );
                    continue;
                }
                let type_id = bda_def.type_ref.as_deref().ok_or_else(|| {
                    CompileError::Emit(format!(
                        "BDA `{}` has bType=Struct but no type_ref; the resolve stage should have rejected it",
                        bda_def.name
                    ))
                })?;
                let sub_dat = dtt.da_types.get(type_id).ok_or_else(|| {
                    CompileError::Emit(format!(
                        "BDA type_ref `{}` is absent from da_types; the resolve stage should have rejected it",
                        type_id
                    ))
                })?;
                let path = format!("{}/SDI[name=\"{}\"]", parent_path, sdi.name);
                base_path.push(sdi.name.clone());
                emit_instances_at_da(&sdi.children, sub_dat, dtt, &path, base_path, out)?;
                base_path.pop();
            }
            RawDataInstance::Dai(dai) => {
                let bda_def = match dat.bdas.iter().find(|b| b.name == dai.name) {
                    Some(b) => b,
                    None => {
                        tracing::warn!(
                            target: "iec61850-scl-build",
                            "DAI name=\"{}\" has no matching BDA in DAType id=\"{}\", skipping",
                            dai.name,
                            dat.id
                        );
                        continue;
                    }
                };
                let path = format!("{}/DAI[name=\"{}\"]", parent_path, dai.name);
                base_path.push(dai.name.clone());
                emit_dai_assignment(
                    dai,
                    bda_def.b_type.as_str(),
                    bda_def.type_ref.as_deref(),
                    dtt,
                    &path,
                    base_path,
                    out,
                )?;
                base_path.pop();
            }
        }
    }
    Ok(())
}

/// Parses one DAI value while the build script runs and emits it as a literal,
/// together with the path lookup on `__ln` and the write.
fn emit_dai_assignment(
    dai: &RawDai,
    b_type: &str,
    type_ref: Option<&str>,
    dtt: &DataTypeTemplates,
    path: &str,
    base_path: &[String],
    out: &mut Vec<TokenStream>,
) -> Result<(), CompileError> {
    if dai.values.is_empty() {
        // No Val element: the DAI only declares valKind or valImport and
        // overrides no value, exactly as at run time.
        return Ok(());
    }
    if b_type == "Struct" {
        return Err(CompileError::Emit(format!(
            "{}: the DAI resolves to a constructed DA (bType=Struct); an SDI is required here, and the runtime path rejects it too",
            path
        )));
    }
    let val = pick_val_for_no_sgroup(&dai.values);
    let parsed: MmsValue = parse_val_for_b_type(val, b_type, type_ref, dtt, dai.span, path)
        .map_err(|e| {
            CompileError::Emit(format!("failed to parse the DAI value at {}: {}", path, e))
        })?;
    let value_tok = emit_mms_value(&parsed);

    // base_path[0] is the DO name; the remaining segments are resolved one level
    // at a time down the LN, DO and DA trees.
    let do_name = base_path
        .first()
        .ok_or_else(|| CompileError::Emit(format!("{}: the DAI override path is empty", path)))?;
    let do_name_lit = do_name.as_str();
    // The middle segments, between the DO and the final DA, are looked up among
    // the DO children as either a SubDo or a Da.
    let mid_segments: Vec<&str> = base_path[1..base_path.len() - 1]
        .iter()
        .map(|s| s.as_str())
        .collect();
    let leaf_name = base_path.last().expect("base_path is non-empty").as_str();

    // A non-empty middle means the path crosses an SDO or a constructed DA, so
    // the lookup descends level by level: `do_by_name` yields the data object;
    // an empty middle takes `child_by_name(leaf)` straight to a `DoChild::Da`;
    // a non-empty middle resolves the intermediate segments first.
    //
    // The whole lookup is emitted as an `if let Some(_)` chain, so a segment
    // that does not resolve is skipped silently, as the runtime path does.
    let stmt = if mid_segments.is_empty() {
        // Straight from the logical node to the data object to the leaf.
        quote! {
            if let ::std::option::Option::Some(__do) = __ln.do_by_name(#do_name_lit) {
                if let ::std::option::Option::Some(::iec61850_scl::__rt::DoChild::Da(__da))
                    = __do.child_by_name(#leaf_name)
                {
                    *__da
                        .value
                        .write()
                        .expect("codegen: MmsValue lock poisoned during DAI override")
                        = #value_tok;
                }
            }
        }
    } else {
        // The middle segments form a SubDo chain whose last element may be a
        // SubDo or a Da, after which the remaining names walk the DA tree.
        //
        // The lookup is emitted as an expanded if-let chain rather than a
        // recursive helper, because emit must not add a free function to the
        // model crate. A middle is rarely more than three levels deep.
        let mid_lits: Vec<&str> = mid_segments.clone();
        emit_nested_lookup_assign(do_name_lit, &mid_lits, leaf_name, value_tok)
    };
    out.push(stmt);
    Ok(())
}

/// Emits the nested lookup from a data object, through a chain of SubDo or DA
/// nodes, to the leaf.
///
/// Expands `do_by_name`, the intermediate `child_by_name` calls and the final
/// write into nested if-lets. A segment that does not resolve is skipped, which
/// mirrors the warn-and-skip behavior of the runtime path.
fn emit_nested_lookup_assign(
    do_name: &str,
    mid_segments: &[&str],
    leaf_name: &str,
    value_tok: TokenStream,
) -> TokenStream {
    // Two shapes of path exist: one where a middle segment resolves to a data
    // attribute and the rest walks the DA tree, and one where every middle
    // segment is a SubDo and the leaf is a child of the last sub-DO.
    //
    // This helper handles the second shape and emits a SubDo chain; the first
    // shape is not routed through it.
    //
    // TODO: emit the DA-tree branch as well, so a middle segment holding a
    // constructed DA is generated the way the runtime path walks it.

    // Join the middle segments into a nested if-let SubDo chain.
    let inner = mid_segments.iter().rfold(
        // Endpoint: `child_by_name(leaf)` on `__cur_do` yields the `DoChild::Da`
        // to write into.
        quote! {
            if let ::std::option::Option::Some(::iec61850_scl::__rt::DoChild::Da(__da))
                = __cur_do.child_by_name(#leaf_name)
            {
                *__da
                    .value
                    .write()
                    .expect("codegen: MmsValue lock poisoned during DAI override")
                    = #value_tok;
            }
        },
        |acc, seg| {
            quote! {
                if let ::std::option::Option::Some(::iec61850_scl::__rt::DoChild::SubDo(__cur_do))
                    = __cur_do.child_by_name(#seg)
                {
                    #acc
                }
            }
        },
    );

    quote! {
        if let ::std::option::Option::Some(__cur_do) = __ln.do_by_name(#do_name) {
            #inner
        }
    }
}

// -----------------------------------------------------------------------------
// Small helpers
// -----------------------------------------------------------------------------

/// Converts an IED name into a valid Rust identifier. The SCL schema allows
/// `[A-Za-z_][A-Za-z0-9_]*`; any other character is stripped for safety.
fn sanitize_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

fn sorted_by_name<'a, T, F>(
    iter: impl Iterator<Item = &'a T>,
    cfg: &CompileBuilder,
    key: F,
) -> Vec<&'a T>
where
    T: 'a,
    F: Fn(&T) -> &str,
{
    let mut v: Vec<&T> = iter.collect();
    if cfg.is_deterministic() {
        v.sort_by(|a, b| key(a).cmp(key(b)));
    }
    v
}

#[cfg(test)]
mod tests {
    use super::*;
    use iec61850_scl::parse_scl;

    #[test]
    fn sanitize_ident_handles_dashes_and_digits() {
        assert_eq!(sanitize_ident("MyIED"), "MyIED");
        assert_eq!(sanitize_ident("foo-bar"), "foo_bar");
        assert_eq!(sanitize_ident("123foo"), "_123foo");
        assert_eq!(sanitize_ident(""), "_");
    }

    fn compile_smoke_xml() -> &'static str {
        // A minimal IED: one LD, LLN0, one further LN (MMXU) and one SPS DOType.
        r#"<SCL>
  <DataTypeTemplates>
    <LNodeType id="LLN0_T" lnClass="LLN0">
      <DO name="Mod" type="ENC_T"/>
      <DO name="Beh" type="ENC_T"/>
    </LNodeType>
    <LNodeType id="MMXU_T" lnClass="MMXU">
      <DO name="A" type="WYE_T"/>
    </LNodeType>
    <DOType id="ENC_T" cdc="ENC">
      <DA name="stVal" fc="ST" bType="Enum" type="ModEnum" dchg="true"/>
      <DA name="q"     fc="ST" bType="Quality" qchg="true"/>
      <DA name="t"     fc="ST" bType="Timestamp"/>
    </DOType>
    <DOType id="WYE_T" cdc="WYE">
      <DA name="phsA" fc="MX" bType="Struct" type="CMV_T" dchg="true"/>
    </DOType>
    <DAType id="CMV_T">
      <BDA name="cVal" bType="FLOAT32"/>
      <BDA name="t" bType="Timestamp"/>
    </DAType>
    <EnumType id="ModEnum">
      <EnumVal ord="1">on</EnumVal>
      <EnumVal ord="2">off</EnumVal>
    </EnumType>
  </DataTypeTemplates>
  <IED name="IED1">
    <AccessPoint name="AP1">
      <Server>
        <LDevice inst="LD0">
          <LN0 inst="" lnType="LLN0_T">
            <DOI name="Mod">
              <DAI name="stVal">
                <Val>on</Val>
              </DAI>
            </DOI>
          </LN0>
          <LN lnClass="MMXU" inst="1" lnType="MMXU_T"/>
        </LDevice>
      </Server>
    </AccessPoint>
  </IED>
</SCL>"#
    }

    fn cfg() -> CompileBuilder {
        crate::compile_icd("dummy.icd")
    }

    /// The emitted tokens must form a valid Rust file, so they go through
    /// `syn::parse2` and `prettyplease`, and the text is then checked for the
    /// expected markers.
    #[test]
    fn emit_smoke_minimal_scl() {
        let raw = parse_scl(compile_smoke_xml()).expect("parse");
        let resolved = raw.resolve().expect("resolve");
        let tokens = emit_file(&resolved, &cfg()).expect("emit_file");
        let file: syn::File = syn::parse2(tokens.clone()).expect("parse2 must succeed");
        let pretty = prettyplease::unparse(&file);

        // Key markers
        assert!(
            pretty.contains("pub fn build_IED1_model"),
            "expected build_<X>_model fn, got:\n{pretty}"
        );
        assert!(
            pretty.contains("IedModelBuilder :: new") || pretty.contains("IedModelBuilder::new")
        );
        assert!(
            pretty.contains("LogicalDeviceBuilder :: new")
                || pretty.contains("LogicalDeviceBuilder::new")
        );
        assert!(
            pretty.contains("LogicalNodeBuilder :: new")
                || pretty.contains("LogicalNodeBuilder::new")
        );
        // The functional constraint variants actually emitted
        assert!(pretty.contains("FC :: St") || pretty.contains("FC::St"));
        assert!(pretty.contains("FC :: Mx") || pretty.contains("FC::Mx"));
        // A constructed DA goes through DataAttribute::constructed
        assert!(
            pretty.contains("DataAttribute :: constructed")
                || pretty.contains("DataAttribute::constructed"),
            "expected CONSTRUCTED DA emit, pretty=\n{pretty}"
        );
        // DOI override: DAI Mod.stVal = on becomes MmsValue::Integer(1)
        assert!(
            pretty.contains("MmsValue :: Integer") || pretty.contains("MmsValue::Integer"),
            "expected DOI override MmsValue::Integer, pretty=\n{pretty}"
        );
    }

    /// Generated code and the runtime build path must produce the same
    /// LD, LN, DO and DA shape for one SCL file.
    ///
    /// The comparison is on a serialized structural summary, because
    /// `Arc<RwLock<MmsValue>>` does not compare directly. That is enough to show
    /// the two walks agree.
    #[test]
    fn emit_structure_summary_matches_runtime() {
        let xml = compile_smoke_xml();
        let raw = parse_scl(xml).expect("parse");
        let resolved = raw.resolve().expect("resolve");

        let runtime_model = resolved.build_model("IED1").expect("build_model");

        // Generated path: emit, parse to confirm the result is syntactically
        // valid, then check the structural markers.
        let tokens = emit_file(&resolved, &cfg()).expect("emit_file");
        let _file: syn::File = syn::parse2(tokens).expect("parse2");

        // The runtime side has one LD and two LNs; LLN0 has two DOs and MMXU has
        // one DO whose phsA is a constructed DA.
        assert_eq!(runtime_model.lds.len(), 1);
        let ld = &runtime_model.lds[0];
        assert_eq!(ld.lns.len(), 2);
        let lln0 = ld.lns.iter().find(|ln| ln.class == "LLN0").expect("LLN0");
        assert_eq!(lln0.dos.len(), 2);
        // DOI override: Mod.stVal must become 1, since "on" has ord=1.
        let mod_do = lln0.do_by_name("Mod").expect("Mod DO");
        let st_val = match mod_do.child_by_name("stVal").expect("Mod.stVal exists") {
            iec61850_scl::__rt::DoChild::Da(da) => da,
            _ => panic!("stVal should be DA"),
        };
        let snapshot = st_val.value.read().expect("lock").clone();
        match snapshot {
            iec61850_scl::__rt::MmsValue::Integer(i) => assert_eq!(i, 1),
            other => panic!("expected Integer(1), got {other:?}"),
        }
    }
}
